export abstract class Constants {
  public static TMAX = 'TMAX';
  public static TMIN = 'TMIN';
  public static TMINF = 'TMINF';
  public static TMAXF = 'TMAXF';
  public static TMINS = 'TMINS';
  public static TMAXS = 'TMAXS';
  public static TMINH = 'TMINH';
  public static TMAXH = 'TMAXH';
  public static TMINW = 'TMINW';
  public static TMAXW = 'TMAXW';
  public static YEAR = 'year';
  public static MONTH = 'month';
  public static DAYS = 'days';
  public static COUNTRIES = [
    { name: 'Antigua and Barbuda', country_code: 'AC' },
    { name: 'United Arab Emirates', country_code: 'AE' },
    { name: 'Afghanistan', country_code: 'AF' },
    { name: 'Algeria', country_code: 'AG' },
    { name: 'Azerbaijan', country_code: 'AJ' },
    { name: 'Albania', country_code: 'AL' },
    { name: 'Armenia', country_code: 'AM' },
    { name: 'Angola', country_code: 'AO' },
    { name: 'American Samoa [United States]', country_code: 'AQ' },
    { name: 'Argentina', country_code: 'AR' },
    { name: 'Australia', country_code: 'AS' },
    { name: 'Austria', country_code: 'AU' },
    { name: 'Antarctica', country_code: 'AY' },
    { name: 'Bahrain', country_code: 'BA' },
    { name: 'Barbados', country_code: 'BB' },
    { name: 'Botswana', country_code: 'BC' },
    { name: 'Bermuda [United Kingdom]', country_code: 'BD' },
    { name: 'Belgium', country_code: 'BE' },
    { name: 'Bahamas, The', country_code: 'BF' },
    { name: 'Bangladesh', country_code: 'BG' },
    { name: 'Belize', country_code: 'BH' },
    { name: 'Bosnia and Herzegovina', country_code: 'BK' },
    { name: 'Bolivia', country_code: 'BL' },
    { name: 'Burma', country_code: 'BM' },
    { name: 'Benin', country_code: 'BN' },
    { name: 'Belarus', country_code: 'BO' },
    { name: 'Solomon Islands', country_code: 'BP' },
    { name: 'Brazil', country_code: 'BR' },
    { name: 'Bulgaria', country_code: 'BU' },
    { name: 'Brunei', country_code: 'BX' },
    { name: 'Burundi', country_code: 'BY' },
    { name: 'Canada', country_code: 'CA' },
    { name: 'Cambodia', country_code: 'CB' },
    { name: 'Chad', country_code: 'CD' },
    { name: 'Sri Lanka', country_code: 'CE' },
    { name: 'Congo (Brazzaville)', country_code: 'CF' },
    { name: 'Congo (Kinshasa)', country_code: 'CG' },
    { name: 'China', country_code: 'CH' },
    { name: 'Chile', country_code: 'CI' },
    { name: 'Cayman Islands [United Kingdom]', country_code: 'CJ' },
    { name: 'Cocos (Keeling) Islands [Australia]', country_code: 'CK' },
    { name: 'Cameroon', country_code: 'CM' },
    { name: 'Colombia', country_code: 'CO' },
    { name: 'Northern Mariana Islands [United States]', country_code: 'CQ' },
    { name: 'Costa Rica', country_code: 'CS' },
    { name: 'Central African Republic', country_code: 'CT' },
    { name: 'Cuba', country_code: 'CU' },
    { name: 'Cape Verde', country_code: 'CV' },
    { name: 'Cook Islands [New Zealand]', country_code: 'CW' },
    { name: 'Cyprus', country_code: 'CY' },
    { name: 'Denmark', country_code: 'DA' },
    { name: 'Dominica', country_code: 'DO' },
    { name: 'Dominican Republic', country_code: 'DR' },
    { name: 'Ecuador', country_code: 'EC' },
    { name: 'Egypt', country_code: 'EG' },
    { name: 'Ireland', country_code: 'EI' },
    { name: 'Equatorial Guinea', country_code: 'EK' },
    { name: 'Estonia', country_code: 'EN' },
    { name: 'Eritrea', country_code: 'ER' },
    { name: 'El Salvador', country_code: 'ES' },
    { name: 'Ethiopia', country_code: 'ET' },
    { name: 'Europa Island [France]', country_code: 'EU' },
    { name: 'Czech Republic', country_code: 'EZ' },
    { name: 'French Guiana [France]', country_code: 'FG' },
    { name: 'Finland', country_code: 'FI' },
    { name: 'Fiji', country_code: 'FJ' },
    {
      name: 'Falkland Islands (Islas Malvinas) [United Kingdom]',
      country_code: 'FK',
    },
    { name: 'Federated States of Micronesia', country_code: 'FM' },
    { name: 'French Polynesia', country_code: 'FP' },
    { name: 'France', country_code: 'FR' },
    {
      name: 'French Southern and Antarctic Lands [France]',
      country_code: 'FS',
    },
    { name: 'Gambia, The', country_code: 'GA' },
    { name: 'Gabon', country_code: 'GB' },
    { name: 'Georgia', country_code: 'GG' },
    { name: 'Ghana', country_code: 'GH' },
    { name: 'Gibraltar [United Kingdom]', country_code: 'GI' },
    { name: 'Greenland [Denmark]', country_code: 'GL' },
    { name: 'Germany', country_code: 'GM' },
    { name: 'Guadeloupe [France]', country_code: 'GP' },
    { name: 'Guam [United States]', country_code: 'GQ' },
    { name: 'Greece', country_code: 'GR' },
    { name: 'Guatemala', country_code: 'GT' },
    { name: 'Guinea', country_code: 'GV' },
    { name: 'Guyana', country_code: 'GY' },
    { name: 'Honduras', country_code: 'HO' },
    { name: 'Croatia', country_code: 'HR' },
    { name: 'Hungary', country_code: 'HU' },
    { name: 'Iceland', country_code: 'IC' },
    { name: 'Indonesia', country_code: 'ID' },
    { name: 'India', country_code: 'IN' },
    {
      name: 'British Indian Ocean Territory [United Kingdom]',
      country_code: 'IO',
    },
    { name: 'Iran', country_code: 'IR' },
    { name: 'Israel', country_code: 'IS' },
    { name: 'Italy', country_code: 'IT' },
    { name: "Cote D'Ivoire", country_code: 'IV' },
    { name: 'Iraq', country_code: 'IZ' },
    { name: 'Japan', country_code: 'JA' },
    { name: 'Jamaica', country_code: 'JM' },
    { name: 'Jan Mayen [Norway]', country_code: 'JN' },
    { name: 'Jordan', country_code: 'JO' },
    { name: 'Johnston Atoll [United States]', country_code: 'JQ' },
    { name: 'Juan De Nova Island [France]', country_code: 'JU' },
    { name: 'Kenya', country_code: 'KE' },
    { name: 'Kyrgyzstan', country_code: 'KG' },
    { name: 'Korea, North', country_code: 'KN' },
    { name: 'Kiribati', country_code: 'KR' },
    { name: 'Korea, South', country_code: 'KS' },
    { name: 'Christmas Island [Australia]', country_code: 'KT' },
    { name: 'Kuwait', country_code: 'KU' },
    { name: 'Kazakhstan', country_code: 'KZ' },
    { name: 'Laos', country_code: 'LA' },
    { name: 'Lebanon', country_code: 'LE' },
    { name: 'Latvia', country_code: 'LG' },
    { name: 'Lithuania', country_code: 'LH' },
    { name: 'Liberia', country_code: 'LI' },
    { name: 'Slovakia', country_code: 'LO' },
    { name: 'Palmyra Atoll [United States]', country_code: 'LQ' },
    { name: 'Lesotho', country_code: 'LT' },
    { name: 'Luxembourg', country_code: 'LU' },
    { name: 'Libya', country_code: 'LY' },
    { name: 'Madagascar', country_code: 'MA' },
    { name: 'Martinique [France]', country_code: 'MB' },
    { name: 'Macau S.A.R', country_code: 'MC' },
    { name: 'Moldova', country_code: 'MD' },
    { name: 'Mayotte [France]', country_code: 'MF' },
    { name: 'Mongolia', country_code: 'MG' },
    { name: 'Malawi', country_code: 'MI' },
    { name: 'Montenegro', country_code: 'MJ' },
    { name: 'Macedonia', country_code: 'MK' },
    { name: 'Mali', country_code: 'ML' },
    { name: 'Morocco', country_code: 'MO' },
    { name: 'Mauritius', country_code: 'MP' },
    { name: 'Midway Islands [United States}', country_code: 'MQ' },
    { name: 'Mauritania', country_code: 'MR' },
    { name: 'Malta', country_code: 'MT' },
    { name: 'Oman', country_code: 'MU' },
    { name: 'Maldives', country_code: 'MV' },
    { name: 'Mexico', country_code: 'MX' },
    { name: 'Malaysia', country_code: 'MY' },
    { name: 'Mozambique', country_code: 'MZ' },
    { name: 'New Caledonia [France]', country_code: 'NC' },
    { name: 'Niue [New Zealand]', country_code: 'NE' },
    { name: 'Norfolk Island [Australia]', country_code: 'NF' },
    { name: 'Niger', country_code: 'NG' },
    { name: 'Vanuatu', country_code: 'NH' },
    { name: 'Nigeria', country_code: 'NI' },
    { name: 'Netherlands', country_code: 'NL' },
    { name: 'Sint Maarten', country_code: 'NN' },
    { name: 'Norway', country_code: 'NO' },
    { name: 'Nepal', country_code: 'NP' },
    { name: 'Suriname', country_code: 'NS' },
    { name: 'Nicaragua', country_code: 'NU' },
    { name: 'New Zealand', country_code: 'NZ' },
    { name: 'Paraguay', country_code: 'PA' },
    { name: 'Pitcairn Islands [United Kingdom]', country_code: 'PC' },
    { name: 'Peru', country_code: 'PE' },
    { name: 'Pakistan', country_code: 'PK' },
    { name: 'Poland', country_code: 'PL' },
    { name: 'Panama', country_code: 'PM' },
    { name: 'Portugal', country_code: 'PO' },
    { name: 'Papua New Guinea', country_code: 'PP' },
    { name: 'Palau', country_code: 'PS' },
    { name: 'Guinea-Bissau', country_code: 'PU' },
    { name: 'Qatar', country_code: 'QA' },
    { name: 'Reunion [France]', country_code: 'RE' },
    { name: 'Serbia', country_code: 'RI' },
    { name: 'Marshall Islands', country_code: 'RM' },
    { name: 'Romania', country_code: 'RO' },
    { name: 'Philippines', country_code: 'RP' },
    { name: 'Puerto Rico [United States]', country_code: 'RQ' },
    { name: 'Russia', country_code: 'RS' },
    { name: 'Rwanda', country_code: 'RW' },
    { name: 'Saudi Arabia', country_code: 'SA' },
    { name: 'Saint Pierre and Miquelon [France]', country_code: 'SB' },
    { name: 'Seychelles', country_code: 'SE' },
    { name: 'South Africa', country_code: 'SF' },
    { name: 'Senegal', country_code: 'SG' },
    { name: 'Saint Helena [United Kingdom]', country_code: 'SH' },
    { name: 'Slovenia', country_code: 'SI' },
    { name: 'Sierra Leone', country_code: 'SL' },
    { name: 'Singapore', country_code: 'SN' },
    { name: 'Spain', country_code: 'SP' },
    { name: 'Saint Lucia', country_code: 'ST' },
    { name: 'Sudan', country_code: 'SU' },
    { name: 'Svalbard [Norway]', country_code: 'SV' },
    { name: 'Sweden', country_code: 'SW' },
    {
      name: 'South Georgia and the South Sandwich Islands [United Kingdom]',
      country_code: 'SX',
    },
    { name: 'Syria', country_code: 'SY' },
    { name: 'Switzerland', country_code: 'SZ' },
    { name: 'Trinidad and Tobago', country_code: 'TD' },
    { name: 'Tromelin Island [France]', country_code: 'TE' },
    { name: 'Thailand', country_code: 'TH' },
    { name: 'Tajikistan', country_code: 'TI' },
    { name: 'Tokelau [New Zealand]', country_code: 'TL' },
    { name: 'Tonga', country_code: 'TN' },
    { name: 'Togo', country_code: 'TO' },
    { name: 'Tunisia', country_code: 'TS' },
    { name: 'Turkey', country_code: 'TU' },
    { name: 'Tuvalu', country_code: 'TV' },
    { name: 'Turkmenistan', country_code: 'TX' },
    { name: 'Tanzania', country_code: 'TZ' },
    { name: 'Curacao', country_code: 'UC' },
    { name: 'Uganda', country_code: 'UG' },
    { name: 'United Kingdom', country_code: 'UK' },
    { name: 'Ukraine', country_code: 'UP' },
    { name: 'United States', country_code: 'US' },
    { name: 'Burkina Faso', country_code: 'UV' },
    { name: 'Uruguay', country_code: 'UY' },
    { name: 'Uzbekistan', country_code: 'UZ' },
    { name: 'Venezuela', country_code: 'VE' },
    { name: 'Vietnam', country_code: 'VM' },
    { name: 'Virgin Islands [United States]', country_code: 'VQ' },
    { name: 'Namibia', country_code: 'WA' },
    { name: 'Wallis and Futuna [France]', country_code: 'WF' },
    { name: 'Western Sahara', country_code: 'WI' },
    { name: 'Wake Island [United States]', country_code: 'WQ' },
    { name: 'Swaziland', country_code: 'WZ' },
    { name: 'Zambia', country_code: 'ZA' },
    { name: 'Zimbabwe', country_code: 'ZI' },
  ];
}
